[build]
  command = "yarn run build"
  functions = "functions"
  publish = "_site"

[dev]
  command = "yarn run dev:all"

[[redirects]]
  from = "/api/music/*"
  to = "/.netlify/functions/music-:splat"
  status = 200
